FROM rocker/rstudio

# system libraries of general use
RUN apt-get update && apt-get install -y \
	bzip2 \
	ca-certificates \
	ca-certificates-java \
	curl \
	default-jre-headless \
	git \
	java-common \
	jq \
	libcairo2-dev \
	libcurl4-gnutls-dev \
	libfontconfig \
	libssl-dev \
	libssh2-1-dev \
	libxml2 \
	libxml2-dev \
	libxt-dev \
	openjdk-11-jre-headless \
	odbc-postgresql \
	pandoc \
	pandoc-citeproc \
	sudo \
	unixodbc \
	unixodbc-dev \
	vim \
	&& mkdir /tmp/phantomjs \
	&& curl -L https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 \
		      | tar -xj --strip-components=1 -C /tmp/phantomjs \
	&& cd /tmp/phantomjs \
	&& mv bin/phantomjs /usr/local/bin \
	&& cd \
	&& apt-get clean \
	&& rm -rf /tmp/* /var/lib/apt/lists/*

    

# Install R packages
RUN install2.r \
	data.tree \
	DBI  \
	dbplyr \
	devtools \
	future \
	here \
	htmlTable\
	iCiteR \
	shiny \
	shinydashboard \
	shinyFeedback \
	shinyhelper \
	shinyjs \
	shinytest\
	shinyTree \
	shinyWidgets \
	odbc \
	plotly \
	rcrossref \
	readr \
	RefManageR \
	rentrez \
	rjson \
	roadoi \
	rorcid \
	RPostgres \
	scholar \
	testthat \
	UpSetR
RUN R -e "devtools::install_github('krassowski/complex-upset')"
RUN R -e "devtools::install_github('ropensci/RefManageR')"
RUN R -e "devtools::install_github('RinteRface/shinydashboardPlus')"
RUN R -e "devtools::install_github('jkeirstead/scholar')"


RUN install2.r stringdist microbenchmark


RUN mkdir /home/shinycannon && \
	cd /home/shinycannon && \
	curl -L https://s3.amazonaws.com/rstudio-shinycannon-build/2019-11-22-20:24:21_1.0.0-9b22a92/deb/shinycannon_1.0.0-9b22a92_amd64.deb > /home/shinycannon/shinycannon_1.0.0-9b22a92_amd64.deb && \
	dpkg -i /home/shinycannon/shinycannon_1.0.0-9b22a92_amd64.deb
RUN R -e "devtools::install_github('rstudio/shinyloadtest')"

COPY odbc.ini /etc
EXPOSE 8787	

# run app
