version: '3.3'

services:
        db:
                build:
                        context: .
                        dockerfile: Dockerfile_db
                env_file:
                        - postgres.env
                volumes:
                        - type: volume
                          source: sql_data_os_monitor
                          target: /var/lib/postgresql/data
                          volume:
                                  nocopy: true
                networks:
                        - db-tier

        shiny:
                build: 
                        context: .
                        dockerfile: Dockerfile_shiny
                ports:
                        - "3838:3838"
                volumes:
                        - type: volume
                          source: shiny_logs
                          target: /var/log/shiny-server
                        - type: volume
                          source: shiny_bookmarks
                          target: /var/lib/shiny-server/bookmarks
                depends_on:
                        - db
                networks:
                        - proxy-tier
                        - db-tier
        translation-server:
                image: zotero/translation-server
                ports: 
                        - "1969:1969"
                expose:
                        - "80"
                        - "443"
                networks:
                        - proxy-tier



volumes:
        sql_data_os_monitor:
                external: true
        shiny_logs:
        shiny_bookmarks:

networks:
        proxy-tier:
        db-tier:
