FROM rocker/shiny-verse

# system libraries of general use
RUN apt-get update && apt-get install -y \
	bzip2 \
	ca-certificates \
	ca-certificates-java \
	curl \
	default-jre-headless \
    	git \
	java-common \
	jq \
	libcurl4-gnutls-dev \
    	libcairo2-dev \
	libfontconfig \
    	libssl-dev \
    	libssh2-1-dev \
    	libxml2 \
    	libxml2-dev \
    	libxt-dev \
	odbc-postgresql \
	openjdk-11-jre-headless \ 
	pandoc \
    	pandoc-citeproc \
	sudo \
	unixodbc \
	unixodbc-dev \
	vim  \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*
  
RUN apt-get update \
      && apt-get install -y --no-install-recommends \
      && mkdir /tmp/phantomjs \
      && curl -L https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 \
              | tar -xj --strip-components=1 -C /tmp/phantomjs \
      && cd /tmp/phantomjs \
      && mv bin/phantomjs /usr/local/bin \
      && cd \
      && rm -rf /tmp/* /var/lib/apt/lists/*



# Install R packages
RUN install2.r \
	data.tree \
	DBI \
	dbplyr \
	devtools \
	future \
	here \
	htmlTable \
	iCiteR \
	mongolite \
	odbc \
	plotly \
	rcrossref \
	readr \
	rentrez \
	rjson \
	roadoi \
	rorcid \
	RPostgres \		
	scholar \
	shiny \
	shinyFeedback \
	shinyhelper \
	shinyjs \
	shinytest \
	shinyTree \
	shinyWidgets \
	testthat \
	UpSetR

RUN R -e "devtools::install_github('krassowski/complex-upset')"
RUN R -e "devtools::install_github('ropensci/RefManageR')"


RUN rm -rf /srv/shiny-server/*
RUN mkdir /srv/shiny-server/apps
COPY shiny_app /srv/shiny-server/apps/zora_oa_app
COPY general_oa_app /srv/shiny-server/apps/general_oa_app
COPY uzhOS /srv/shiny-server/uzhOS
COPY analysis /srv/shiny-server/analysis
COPY data /srv/shiny-server/data
COPY shiny-server.conf /etc/shiny-server
COPY update_zora.sh /home
COPY odbc.ini /etc
COPY data/orgtree.rds /srv/shiny-server/data/
COPY data/fac_dep_filt.rds /srv/shiny-server/data/

EXPOSE 3839
# allow permission
RUN sudo chown -R shiny:shiny /srv/shiny-server

RUN mkdir -p /var/log/shiny-server/zora_oa_app
RUN mkdir -p /var/log/shiny-server/general_oa_app
# run app
