version: '3.3'
services:
        db:
                build:
                        context: .
                        dockerfile: Dockerfile_db
                environment:
                        POSTGRES_PASSWORD: flora
                        POSTGRES_USER: shiny
                        POSTGRES_DB: oa
                volumes:
                        - type: volume
                          source: sql_data_os_monitor
                          target: /var/lib/postgresql/data
                          volume:
                                  nocopy: true



        rstudio:
                build: 
                        context: .
                        dockerfile: Dockerfile_rstudio
                environment:
                        PASSWORD: flora
                volumes:
                        - type: bind
                          source: /home/reto/Nextcloud/Projects/open_access/os_monitor
                          target: /srv/shiny-server/os_monitor

                ports:
                        - "8787:8787"

        translation-server:
                image: zotero/translation-server
                ports: 
                        - "1969:1969"
                expose:
                        - "80"
                        - "443"

volumes:
        sql_data_os_monitor:
                external: true
