skip_on_ci()
testthat::test_that("retrieve_from_publons correct",{
  mr_publons <- retrieve_from_publons("0000-0002-3048-5518")
  expect_true(all(names(mr_publons) %in% c("title","doi","date","year","in_publons")))
  expect_equal(typeof(mr_publons$year),"integer")
  expect_equal(typeof(mr_publons$in_publons),"logical")
  mr_publons <- retrieve_from_publons("noreport")
  expect_true(all(names(mr_publons) %in% c("title","doi","date","year","in_publons")))
  expect_equal(typeof(mr_publons$year),"integer")
  expect_equal(typeof(mr_publons$in_publons),"logical")
  mr_publons <- retrieve_from_publons("0000-0000-0000-0000")
  expect_true(all(names(mr_publons) %in% c("title","doi","date","year","in_publons")))
  expect_equal(typeof(mr_publons$year),"integer")
  expect_equal(typeof(mr_publons$in_publons),"logical")
})