#' UI module Orcid input
#'
#' @param id namespace
#'
#' @import shiny
#' @export
inputOrcidUI <- function(id) {
  ns <- NS(id)
  tagList(
    textInput(ns("orcid"),
              label = a("Orcid",
                        href="https://orcid.org",
                        target="_blank"), 
              value="")
  )
}

#' UI module Pubmed input
#'
#' @param id namespace
#'
#' @import shiny
#' @export
inputPubmedUI <- function(id) {
  ns <- NS(id)
  tagList(
    # splitLayout(cellWidths = c("65%", "25%","10%"),
    fluidRow(
             column(width = 8,
                textAreaInput(ns("pubmed"),
                              label = a("Pubmed Query",
                                        href= "https://www.ncbi.nlm.nih.gov/books/NBK3827/#pubmedhelp.How_do_I_search_by_author",
                                        target="_blank"), 
                              value="",
                              placeholder="To activate, click on 'Example Pubmed Query'") %>% 
                  shinyjs::disabled(),
             ), 
             column(width = 2,
                actionButton(ns("activate_pubmed"),
                             HTML("Example <br/> Pubmed <br/> Query")),
             ),
             column(width = 2,
                shinyWidgets::dropdown(style = "stretch", status= "primary", tooltip = shinyWidgets::tooltipOptions(title = "Help"),
                  icon=icon("question"),
                  div(style="width:500px",
                    p("To retrieve publications from Pubmed a query has to be specified. 
                      An example query with a dummy name can generated by pressing 'Example Pubmed Query'."),
                    a("Additional information can found here.",
                      href= "https://www.ncbi.nlm.nih.gov/books/NBK3827/#pubmedhelp.How_do_I_search_by_author",
                      target="_blank"),
                    p("The following is a list of possible tags to use in a Pubmed query:"), 
                    verbatimTextOutput(ns("info_pubmed"))
                  )
                )
             )
          )
  )
}

#' UI module Scholar input
#'
#' @param id namespace
#'
#' @import shiny
#' @export
inputScholarUI <- function(id) {
  ns <- NS(id)
  tagList(
    textInput(ns("scholar"),
              label = a("Google Scholar id",
                        href="https://scholar.google.ch",
                        target="_blank"), 
              value="") %>% 
      shinyhelper::helper(type="markdown",
                          title = "Google scholar id help",
                          content = 'Google_scholar_help'),
    shinyWidgets::prettySwitch(inputId = ns("scholar_matching_with_zotero"),
                               label = "Use Zotero to retrieve DOI of publications.", 
                               value = FALSE,
                               fill = TRUE, status = "primary"), 
    # scholar match with crossref
    shinyWidgets::prettySwitch(inputId = ns("scholar_matching_with_crossref"),
                               label = "Use Crossref for increased accuracy in matching publications.", 
                               value = FALSE,
                               fill = TRUE, status = "primary") 
  )
}

#' UI module Publons input
#'
#' @param id namespace
#'
#' @import shiny
#' @export
inputPublonsUI <- function(id) {
  ns <- NS(id)
  tagList(
    textInput(ns("publons"),
              label = tags$div(tags$a("Publons id",
                                      href="https://publons.com",target="_blank"),
                               tags$span(class="help-block","(or if linked: ORCID, ResearcherID or TRUID)")), 
              value="")
  )
}
